<?php require_once APPROOT . '/views/includes/header.php'; ?>

<div class="container mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <div class="flex justify-between items-center mb-6">
        <h1 class="text-3xl font-bold text-gray-800"><?= htmlspecialchars($data['page_main_title']) ?></h1>
        <a href="<?= URLROOT ?>/referral/dashboard" class="text-sm text-blue-600 hover:underline">&larr; Back to Admin Dashboard</a>
    </div>

    <!-- Visits Table -->
    <div class="bg-white rounded-lg shadow-md overflow-hidden">
        <div class="p-4 sm:p-6">
            <h2 class="text-xl font-semibold text-gray-700">All Recorded Visits</h2>
            <p class="mt-1 text-sm text-gray-500">A log of every visit generated by this marketer's referral link.</p>
        </div>
        <div class="overflow-x-auto">
            <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                    <tr>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">IP Address</th>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Location</th>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Device</th>
                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Registration Status</th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                    <?php if (empty($data['visits'])): ?>
                        <tr>
                            <td colspan="5" class="px-6 py-4 text-center text-gray-500">No visits recorded yet.</td>
                        </tr>
                    <?php else: ?>
                        <?php foreach ($data['visits'] as $visit): ?>
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900"><?= date('Y-m-d H:i', strtotime($visit['visit_recorded_at'])) ?></td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 font-mono"><?= htmlspecialchars($visit['ip_address']) ?></td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><?= htmlspecialchars(implode(', ', array_filter([$visit['city'], $visit['country']]))) ?: 'N/A' ?></td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    <div><?= htmlspecialchars($visit['device_type'] ?? 'N/A') ?></div>
                                    <div class="text-xs"><?= htmlspecialchars($visit['browser_name'] ?? '') ?> on <?= htmlspecialchars($visit['operating_system'] ?? '') ?></div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full 
                                        <?php 
                                            switch ($visit['registration_status']) {
                                                case 'successful': echo 'bg-green-100 text-green-800'; break;
                                                case 'duplicate_phone': echo 'bg-yellow-100 text-yellow-800'; break;
                                                case 'failed_other': echo 'bg-red-100 text-red-800'; break;
                                                default: echo 'bg-gray-100 text-gray-800'; break;
                                            }
                                        ?>">
                                        <?= htmlspecialchars(ucfirst(str_replace('_', ' ', $visit['registration_status']))) ?>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php require_once APPROOT . '/views/includes/footer.php'; ?> 